@startuml
interface Token {
    TokenType type
    String value
    Location location
}

class Assignation implements Token {
    TokenType type
    String value
    Location location
}

class Identifier implements Token {
    TokenType type
    String value
    Location location
}

class StringType implements Token {
    TokenType type
    String value
    Location location
}

class SemiColon implements Token {
    TokenType type
    String value
    Location location
}
' Con Key_Word me refiero a PUBLIC o FINAL y sus variantes
class Key_Word implements Token {
    TokenType type
    String value
    Location location
}
@enduml