name: continuous deployment

on:
    push:
        branches:
            - main # incluyo solo la branch main
jobs:
    deployment:
        runs-on: ubuntu-latest

        # corre en el entorno de producción.
        environment: production

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up JDK
                uses: actions/setup-java@v2
                with:
                    java-version: 11
                    distribution: 'adopt'

            #buildeo para chequear q se esté aplicando la CI.
            #Si cd se hace luego de ci, no haría falta.
            -   name: Run Build
                run: ./gradlew build

            # en build.gradle se define a donde se va a publicar.
            -   name: Publish package
                run: ./gradlew publish --info
                env:
                    # actor de github q lo ejecuta
                    GITHUB_ACTOR: ${{ github.actor }}

                    # autentico la publicación del paquete.
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

