name: Continuous Deployment

on:
    push:
        branches:
            - main  # Trigger only on the main branch

jobs:
    deployment:
        runs-on: ubuntu-latest

        # Run in the production environment
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v3  # Use the correct version of checkout action

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: 'adopt'

            # Build the project to ensure CI is applied before CD
            - name: Run Build
              run: ./gradlew build

            # Publish the package
            - name: Publish Package
              run: ./gradlew publish --info
              env:
                  # Use GITHUB_ACTOR provided by GitHub Actions or set a default value
                  GITHUB_ACTOR: ${{ github.actor || 'default-actor' }}
                  # Use GITHUB_TOKEN provided by GitHub Secrets
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # Optionally, add a step to ensure Gradle has executable permissions
            - name: Make Gradlew Executable
              run: chmod +x ./gradlew
