on:
    push:
        branches:
            - master # incluyo solo la branch master
    pull_request:
        branches:
            - master
jobs:
    ciTasks:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 11

            -   name: Run Build
                run: ./gradlew build

            -   name: Run Tests
                run: ./gradlew test

            -   name: Run coverage check
                run: ./gradlew :koverVerify

            -   name: Run Linter
                run: ./gradlew ktlintCheck

            # no corro formatter en pipeline.
            # -   name: Run formatter
            #    run: ./gradlew ktlintFormat

name: continuous integration
